<?php

return [
    [
        "title" => "Villa Front Lake",
        "category" => "Casa",
        "address" => "Via E. Caronti, 5, 22020 Blevio CO",
        "price" => 950.00,
        "n_rooms" => 7,
        "n_bathrooms" => 7,
        "n_beds" => 7,
        "square_meters" => 650,
        "cover_image" => "uploads/villa-front-lake.webp",
        "is_visible" => 1
    ],
    [
        "title" => "Skylinemilan",
        "category" => "Appartamento",
        "address" => "Via Benedetto Marcello, 34, 20124 Milano MI",
        "price" => 250.00,
        "n_rooms" => 2,
        "n_bathrooms" => 3,
        "n_beds" => 2,
        "square_meters" => 250,
        "cover_image" => "uploads/skylinemilan.webp",
        "is_visible" => 1
    ],
    [
        "title" => "Al Capanno",
        "category" => "Casa",
        "address" => "Via S. Maria, 10, 22020 Occagno CO",
        "price" => 174.00,
        "n_rooms" => 1,
        "n_bathrooms" => 1,
        "n_beds" => 1,
        "square_meters" => 84,
        "cover_image" => "uploads/al-capanno.webp",
        "is_visible" => 0
    ],
    [
        "title" => "Suite at Porto",
        "category" => "Casa",
        "address" => "Piazza Bossi, 21050 Porto Ceresio VA",
        "price" => 150.00,
        "n_rooms" => 1,
        "n_bathrooms" => 1,
        "n_beds" => 1,
        "square_meters" => 96,
        "cover_image" => "uploads/suite-at-porto.webp",
        "is_visible" => 1
    ],
    [
        "title" => "Accogliente appartamento con vista mozzafiato",
        "category" => "Appartamento",
        "address" => "Via Galileo Galilei, 12, 20124 Milano MI",
        "price" => 70.00,
        "n_rooms" => 1,
        "n_bathrooms" => 1,
        "n_beds" => 2,
        "square_meters" => 56,
        "cover_image" => "uploads/accogliente-appartamento-con-vista-mozzafiato.webp",
        "is_visible" => 1
    ],
    [
        "title" => "Bric d'Alù | B&B a Barbaresco con piscina",
        "category" => "B&B",
        "address" => "Str. Rabaja, 21, 12050 Barbaresco CN",
        "price" => 253.00,
        "n_rooms" => 1,
        "n_bathrooms" => 1,
        "n_beds" => 1,
        "square_meters" => 23,
        "cover_image" => "uploads/bric-d-alu.webp",
        "is_visible" => 1
    ],
    [
        "title" => "Casa Lago - Matrimoniale lago - Agriturismo Scraleca",
        "category" => "B&B",
        "address" => "Località, Via Rodino, 25040 Angolo Terme BS",
        "price" => 140.00,
        "n_rooms" => 1,
        "n_bathrooms" => 1,
        "n_beds" => 1,
        "square_meters" => 26,
        "cover_image" => "uploads/casa-lago-matrimoniale-lago-agriturismo-scraleca.webp",
        "is_visible" => 1
    ],
    [
        "title" => "Rifugio esclusivo sul Lago di Como",
        "category" => "Casa",
        "address" => "Via Borgovecchio, 9, 22020 Nesso CO",
        "price" => 500.00,
        "n_rooms" => 4,
        "n_bathrooms" => 2,
        "n_beds" => 5,
        "square_meters" => 76,
        "cover_image" => "uploads/rifugio-esclusivo-sul-lago-di-como.webp",
        "is_visible" => 1
    ],
    [
        "title" => "Casa Panorama",
        "category" => "Casa",
        "address" => "Via Posillipo, 40, 80123 Napoli NA",
        "price" => 65.00,
        "n_rooms" => 2,
        "n_bathrooms" => 1,
        "n_beds" => 1,
        "square_meters" => 15,
        "cover_image" => "uploads/casa-panorama.webp",
        "is_visible" => 1
    ],
    [
        "title" => "Attico Panoramico",
        "category" => "Casa",
        "address" => "Via Domenico Fontana, 80128 Napoli NA",
        "price" => 145.00,
        "n_rooms" => 2,
        "n_bathrooms" => 1,
        "n_beds" => 1,
        "square_meters" => 83,
        "cover_image" => "uploads/attico-panoramico.webp",
        "is_visible" => 1
    ],
    [
        "title" => "Casa sull'acqua con discesa a mare privata",
        "category" => "Casa",
        "address" => "Via Posillipo, 283, 80123 Napoli NA",
        "price" => 180.00,
        "n_rooms" => 1,
        "n_bathrooms" => 5,
        "n_beds" => 1,
        "square_meters" => 95,
        "cover_image" => "uploads/casa-sull-acqua-con-discesa-a-mare-privata.webp",
        "is_visible" => 1
    ],
    [
        "title" => "LUXURY In Posillipo-Private Beach",
        "category" => "Casa",
        "address" => "Via Posillipo, 286, 80123 Napoli NA",
        "price" => 346.00,
        "n_rooms" => 3,
        "n_bathrooms" => 2,
        "n_beds" => 4,
        "square_meters" => 135,
        "cover_image" => "uploads/luxury-in-posillipo-private-beach.webp",
        "is_visible" => 1
    ],
    [
        "title" => "Naima Sea View - Apt di design con vista mare",
        "category" => "Appartamento",
        "address" => "Via Aniello Falcone, 262, 80127 Napoli NA",
        "price" => 177.00,
        "n_rooms" => 2,
        "n_bathrooms" => 1,
        "n_beds" => 5,
        "square_meters" => 148,
        "cover_image" => "uploads/naima-sea-view-apt-di-design-con-vista-mare.webp",
        "is_visible" => 0
    ],
    [
        "title" => "Terrazza Panorama Vomero",
        "category" => "Appartamento",
        "address" => "2ª Trav, Via Giuseppe Bonito, 7, 80129 Napoli NA",
        "price" => 131.00,
        "n_rooms" => 1,
        "n_bathrooms" => 1,
        "n_beds" => 2,
        "square_meters" => 43,
        "cover_image" => "uploads/terrazza-panorama-vomero.webp",
        "is_visible" => 1
    ],
    [
        "title" => "Casa Faro - Borgo dei Saraceni",
        "category" => "Casa",
        "address" => "Via Faro, 84043 Agropoli SA",
        "price" => 113.00,
        "n_rooms" => 1,
        "n_bathrooms" => 1,
        "n_beds" => 2,
        "square_meters" => 63,
        "cover_image" => "uploads/casa-faro-borgo-dei-saraceni.webp",
        "is_visible" => 1
    ],
    [
        "title" => "Esclusivo alloggio a sfioro sul mare con terrazza.",
        "category" => "Appartamento",
        "address" => "Corso Beato Simeone, 84048 Santa Maria di Castellabate SA",
        "price" => 4030.00,
        "n_rooms" => 2,
        "n_bathrooms" => 1,
        "n_beds" => 2,
        "square_meters" => 223,
        "cover_image" => "uploads/esclusivo-alloggio-a-sfioro-sul-mare-con-terrazza.webp",
        "is_visible" => 1
    ],
    [
        "title" => "Villetta a Castellabate",
        "category" => "Casa",
        "address" => "Punta Licosa, 84048 Castellabate SA",
        "price" => 300.00,
        "n_rooms" => 1,
        "n_bathrooms" => 2,
        "n_beds" => 2,
        "square_meters" => 216,
        "cover_image" => "uploads/villetta-a-castellabate.webp",
        "is_visible" => 1
    ],
    [
        "title" => "Panoramic Super Villa on the Beach",
        "category" => "Casa",
        "address" => "Corso Armando Diaz, 63, 84043 Agropoli SA",
        "price" => 63.00,
        "n_rooms" => 1,
        "n_bathrooms" => 2,
        "n_beds" => 2,
        "square_meters" => 186,
        "cover_image" => "uploads/panoramic-super-villa-on-the-beach.webp",
        "is_visible" => 1
    ],
    [
        "title" => "Bed and breakfast Da Marco",
        "category" => "B&B",
        "address" => "Via Vittorio Emanuele, 34, 84090 Montecorvino Pugliano SA",
        "price" => 100.00,
        "n_rooms" => 1,
        "n_bathrooms" => 1,
        "n_beds" => 1,
        "square_meters" => 56,
        "cover_image" => "uploads/bed-and-breakfast-da-marco.webp",
        "is_visible" => 0
    ],
    [
        "title" => "Villa Odabella",
        "category" => "Casa",
        "address" => "SP81, 54, 81037 Rongolisi CE",
        "price" => 358.00,
        "n_rooms" => 5,
        "n_bathrooms" => 2,
        "n_beds" => 6,
        "square_meters" => 156,
        "cover_image" => "uploads/villa-odabella.webp",
        "is_visible" => 1
    ],
    [
        "title" => "VILLA STORICA DI LUSSO IN TOTALE PRIVACY",
        "category" => "Casa",
        "address" =>  "Via Giovanni Augustariccio, 23, 84011 Amalfi SA",
        "price" => 3520.00,
        "n_rooms" => 9,
        "n_bathrooms" => 8,
        "n_beds" => 9,
        "square_meters" => 456,
        "cover_image" => "uploads/villa-storica-di-lusso-in-totale-privacy.webp",
        "is_visible" => 1
    ],
    [
        "title" => "Villa Roxana camera Rosa",
        "category" => "Casa",
        "address" =>  "Via Igino Giordani, 9/A, 00019 Tivoli RM",
        "price" => 50.00,
        "n_rooms" => 1,
        "n_bathrooms" => 1,
        "n_beds" => 1,
        "square_meters" => 26,
        "cover_image" => "uploads/villa-roxana-camera-rosa.webp",
        "is_visible" => 1
    ],
    [
        "title" => "Attico terrazzato Ariccia",
        "category" => "Appartamento",
        "address" =>  "Via Flora, 2, 00040 Ariccia RM",
        "price" => 70.00,
        "n_rooms" => 1,
        "n_bathrooms" => 1,
        "n_beds" => 4,
        "square_meters" => 86,
        "cover_image" => "uploads/attico-terrazzato-ariccia.webp",
        "is_visible" => 1
    ],
    [
        "title" => "Green Empathy Lake Terraces",
        "category" => "Appartamento",
        "address" =>  "SP71b, 9, 00040 Castel Gandolfo RM",
        "price" => 140.00,
        "n_rooms" => 1,
        "n_bathrooms" => 1,
        "n_beds" => 3,
        "square_meters" => 101,
        "cover_image" => "uploads/green-empathy-lake-terraces.webp",
        "is_visible" => 1
    ],
    [
        "title" => "Castel Gandolfo centro storico, vista lago",
        "category" => "Appartamento",
        "address" =>  "Viale Pio XI, 5, 00073 Castel Gandolfo RM",
        "price" => 135.00,
        "n_rooms" => 1,
        "n_bathrooms" => 1,
        "n_beds" => 2,
        "square_meters" => 71,
        "cover_image" => "uploads/castel-gandolfo-centro-storico-vista-lago.webp",
        "is_visible" => 1
    ],
    [
        "title" => "Accogliente Nemi",
        "category" => "Appartamento",
        "address" =>  "Piazza Umberto I, 2, 00040 Nemi RM",
        "price" => 110.00,
        "n_rooms" => 1,
        "n_bathrooms" => 1,
        "n_beds" => 2,
        "square_meters" => 93,
        "cover_image" => "uploads/accogliente-nemi.webp",
        "is_visible" => 0
    ],
    [
        "title" => "Stupenda Doppia Termini Bagno privato Roma Centro",
        "category" => "Appartamento",
        "address" =>  "Via Alfredo Cappellini, 28, 00185 Roma RM",
        "price" => 106.00,
        "n_rooms" => 1,
        "n_bathrooms" => 1,
        "n_beds" => 1,
        "square_meters" => 43,
        "cover_image" => "uploads/stupenda-doppia-termini-bagno-privato-roma-centro.webp",
        "is_visible" => 1
    ]
];
