<?php

return [
  [
    "title" => "Villa Front Lake",
    "category" => "Casa",
    "address" => "Via E. Caronti, 5, 22020 Blevio CO",
    "price" => 950.00,
    "n_rooms" => 7,
    "n_bathrooms" => 7,
    "n_beds" => 7,
    "square_meters" => 650,
    "cover_image" => "uploads/villa-front-lake.webp",
    "is_visible" => 1
  ],
  [
    "title" => "Skylinemilan",
    "category" => "Appartamento",
    "address" => "Via Benedetto Marcello, 34, 20124 Milano MI",
    "price" => 250.00,
    "n_rooms" => 2,
    "n_bathrooms" => 3,
    "n_beds" => 2,
    "square_meters" => 250,
    "cover_image" => "uploads/skylinemilan.webp",
    "is_visible" => 1
  ],
  [
    "title" => "Al Capanno",
    "category" => "Casa",
    "address" => "Via S. Maria, 10, 22020 Occagno CO",
    "price" => 174.00,
    "n_rooms" => 1,
    "n_bathrooms" => 1,
    "n_beds" => 1,
    "square_meters" => 84,
    "cover_image" => "uploads/al-capanno.webp",
    "is_visible" => 0
  ],
  [
    "title" => "Suite at Porto",
    "category" => "Casa",
    "address" => "Piazza Bossi, 21050 Porto Ceresio VA",
    "price" => 150.00,
    "n_rooms" => 1,
    "n_bathrooms" => 1,
    "n_beds" => 1,
    "square_meters" => 96,
    "cover_image" => "uploads/suite-at-porto.webp",
    "is_visible" => 1
  ],
  [
    "title" => "Accogliente appartamento con vista mozzafiato",
    "category" => "Appartamento",
    "address" => "Via Galileo Galilei, 12, 20124 Milano MI",
    "price" => 70.00,
    "n_rooms" => 1,
    "n_bathrooms" => 1,
    "n_beds" => 2,
    "square_meters" => 56,
    "cover_image" => "uploads/accogliente-appartamento-con-vista-mozzafiato.webp",
    "is_visible" => 1
  ],
  [
    "title" => "Bric d'Alù | B&B a Barbaresco con piscina",
    "category" => "B&B",
    "address" => "Str. Rabaja, 21, 12050 Barbaresco CN",
    "price" => 253.00,
    "n_rooms" => 1,
    "n_bathrooms" => 1,
    "n_beds" => 1,
    "square_meters" => 23,
    "cover_image" => "uploads/bric-d-alu.webp",
    "is_visible" => 1
  ],
  [
    "title" => "Casa Lago - Matrimoniale lago - Agriturismo Scraleca",
    "category" => "B&B",
    "address" => "Località, Via Rodino, 25040 Angolo Terme BS",
    "price" => 140.00,
    "n_rooms" => 1,
    "n_bathrooms" => 1,
    "n_beds" => 1,
    "square_meters" => 26,
    "cover_image" => "uploads/casa-lago-matrimoniale-lago-agriturismo-scraleca.webp",
    "is_visible" => 1
  ],
  [
    "title" => "Rifugio esclusivo sul Lago di Como",
    "category" => "Casa",
    "address" => "Via Borgovecchio, 9, 22020 Nesso CO",
    "price" => 500.00,
    "n_rooms" => 4,
    "n_bathrooms" => 2,
    "n_beds" => 5,
    "square_meters" => 76,
    "cover_image" => "uploads/rifugio-esclusivo-sul-lago-di-como.webp",
    "is_visible" => 1
  ],
  [
    "title" => "Casa Panorama",
    "category" => "Casa",
    "address" => "Via Posillipo, 40, 80123 Napoli NA",
    "price" => 65.00,
    "n_rooms" => 2,
    "n_bathrooms" => 1,
    "n_beds" => 1,
    "square_meters" => 15,
    "cover_image" => "uploads/casa-panorama.webp",
    "is_visible" => 1
  ],
  [
    "title" => "Attico Panoramico",
    "category" => "Casa",
    "address" => "Via Domenico Fontana, 80128 Napoli NA",
    "price" => 145.00,
    "n_rooms" => 2,
    "n_bathrooms" => 1,
    "n_beds" => 1,
    "square_meters" => 83,
    "cover_image" => "uploads/attico-panoramico.webp",
    "is_visible" => 1
  ],
  [
    "title" => "Casa sull'acqua con discesa a mare privata",
    "category" => "Casa",
    "address" => "Via Posillipo, 283, 80123 Napoli NA",
    "price" => 180.00,
    "n_rooms" => 1,
    "n_bathrooms" => 5,
    "n_beds" => 1,
    "square_meters" => 95,
    "cover_image" => "uploads/casa-sull-acqua-con-discesa-a-mare-privata.webp",
    "is_visible" => 1
  ],
  [
    "title" => "LUXURY In Posillipo-Private Beach",
    "category" => "Casa",
    "address" => "Via Posillipo, 286, 80123 Napoli NA",
    "price" => 346.00,
    "n_rooms" => 3,
    "n_bathrooms" => 2,
    "n_beds" => 4,
    "square_meters" => 135,
    "cover_image" => "uploads/luxury-in-posillipo-private-beach.webp",
    "is_visible" => 1
  ],
  [
    "title" => "Naima Sea View - Apt di design con vista mare",
    "category" => "Appartamento",
    "address" => "Via Aniello Falcone, 262, 80127 Napoli NA",
    "price" => 177.00,
    "n_rooms" => 2,
    "n_bathrooms" => 1,
    "n_beds" => 5,
    "square_meters" => 148,
    "cover_image" => "uploads/naima-sea-view-apt-di-design-con-vista-mare.webp",
    "is_visible" => 0
  ],
  [
    "title" => "Terrazza Panorama Vomero",
    "category" => "Appartamento",
    "address" => "2ª Trav, Via Giuseppe Bonito, 7, 80129 Napoli NA",
    "price" => 131.00,
    "n_rooms" => 1,
    "n_bathrooms" => 1,
    "n_beds" => 2,
    "square_meters" => 43,
    "cover_image" => "uploads/terrazza-panorama-vomero.webp",
    "is_visible" => 1
  ],
  [
    "title" => "Casa Faro - Borgo dei Saraceni",
    "category" => "Casa",
    "address" => "Via Faro, 84043 Agropoli SA",
    "price" => 113.00,
    "n_rooms" => 1,
    "n_bathrooms" => 1,
    "n_beds" => 2,
    "square_meters" => 63,
    "cover_image" => "uploads/casa-faro-borgo-dei-saraceni.webp",
    "is_visible" => 1
  ],
  [
    "title" => "Esclusivo alloggio a sfioro sul mare con terrazza.",
    "category" => "Appartamento",
    "address" => "Corso Beato Simeone, 84048 Santa Maria di Castellabate SA",
    "price" => 4030.00,
    "n_rooms" => 2,
    "n_bathrooms" => 1,
    "n_beds" => 2,
    "square_meters" => 223,
    "cover_image" => "uploads/esclusivo-alloggio-a-sfioro-sul-mare-con-terrazza.webp",
    "is_visible" => 1
  ],
  [
    "title" => "Villetta a Castellabate",
    "category" => "Casa",
    "address" => "Punta Licosa, 84048 Castellabate SA",
    "price" => 300.00,
    "n_rooms" => 1,
    "n_bathrooms" => 2,
    "n_beds" => 2,
    "square_meters" => 216,
    "cover_image" => "uploads/villetta-a-castellabate.webp",
    "is_visible" => 1
  ],
  [
    "title" => "Panoramic Super Villa on the Beach",
    "category" => "Casa",
    "address" => "Corso Armando Diaz, 63, 84043 Agropoli SA",
    "price" => 63.00,
    "n_rooms" => 1,
    "n_bathrooms" => 2,
    "n_beds" => 2,
    "square_meters" => 186,
    "cover_image" => "uploads/panoramic-super-villa-on-the-beach.webp",
    "is_visible" => 1
  ],
  [
    "title" => "Bed and breakfast Da Marco",
    "category" => "B&B",
    "address" => "Via Vittorio Emanuele, 34, 84090 Montecorvino Pugliano SA",
    "price" => 100.00,
    "n_rooms" => 1,
    "n_bathrooms" => 1,
    "n_beds" => 1,
    "square_meters" => 56,
    "cover_image" => "uploads/bed-and-breakfast-da-marco.webp",
    "is_visible" => 0
  ],
  [
    "title" => "Villa Odabella",
    "category" => "Casa",
    "address" => "SP81, 54, 81037 Rongolisi CE",
    "price" => 358.00,
    "n_rooms" => 5,
    "n_bathrooms" => 2,
    "n_beds" => 6,
    "square_meters" => 156,
    "cover_image" => "uploads/villa-odabella.webp",
    "is_visible" => 1
  ],
  [
    "title" => "Villa storica di lusso in totale privacy",
    "category" => "Casa",
    "address" =>  "Via Giovanni Augustariccio, 23, 84011 Amalfi SA",
    "price" => 3520.00,
    "n_rooms" => 9,
    "n_bathrooms" => 8,
    "n_beds" => 9,
    "square_meters" => 456,
    "cover_image" => "uploads/villa-storica-di-lusso-in-totale-privacy.webp",
    "is_visible" => 1
  ],
  [
    "title" => "Villa Roxana camera Rosa",
    "category" => "Casa",
    "address" =>  "Via Igino Giordani, 9/A, 00019 Tivoli RM",
    "price" => 50.00,
    "n_rooms" => 1,
    "n_bathrooms" => 1,
    "n_beds" => 1,
    "square_meters" => 26,
    "cover_image" => "uploads/villa-roxana-camera-rosa.webp",
    "is_visible" => 1
  ],
  [
    "title" => "Attico terrazzato Ariccia",
    "category" => "Appartamento",
    "address" =>  "Via Flora, 2, 00040 Ariccia RM",
    "price" => 70.00,
    "n_rooms" => 1,
    "n_bathrooms" => 1,
    "n_beds" => 4,
    "square_meters" => 86,
    "cover_image" => "uploads/attico-terrazzato-ariccia.webp",
    "is_visible" => 1
  ],
  [
    "title" => "Green Empathy Lake Terraces",
    "category" => "Appartamento",
    "address" =>  "SP71b, 9, 00040 Castel Gandolfo RM",
    "price" => 140.00,
    "n_rooms" => 1,
    "n_bathrooms" => 1,
    "n_beds" => 3,
    "square_meters" => 101,
    "cover_image" => "uploads/green-empathy-lake-terraces.webp",
    "is_visible" => 1
  ],
  [
    "title" => "Castel Gandolfo centro storico, vista lago",
    "category" => "Appartamento",
    "address" =>  "Viale Pio XI, 5, 00073 Castel Gandolfo RM",
    "price" => 135.00,
    "n_rooms" => 1,
    "n_bathrooms" => 1,
    "n_beds" => 2,
    "square_meters" => 71,
    "cover_image" => "uploads/castel-gandolfo-centro-storico-vista-lago.webp",
    "is_visible" => 1
  ],
  [
    "title" => "Accogliente Nemi",
    "category" => "Appartamento",
    "address" =>  "Piazza Umberto I, 2, 00040 Nemi RM",
    "price" => 110.00,
    "n_rooms" => 1,
    "n_bathrooms" => 1,
    "n_beds" => 2,
    "square_meters" => 93,
    "cover_image" => "uploads/accogliente-nemi.webp",
    "is_visible" => 0
  ],
  [
    "title" => "Stupenda Doppia Termini Bagno privato Roma Centro",
    "category" => "Appartamento",
    "address" =>  "Via Alfredo Cappellini, 28, 00185 Roma RM",
    "price" => 106.00,
    "n_rooms" => 1,
    "n_bathrooms" => 1,
    "n_beds" => 1,
    "square_meters" => 43,
    "cover_image" => "uploads/stupenda-doppia-termini-bagno-privato-roma-centro.webp",
    "is_visible" => 1
  ],
  [
    "title" => "Jazz House - Roma!",
    "category" => "Appartamento",
    "address" =>  "Via Varna, 29, 00124 Roma RM",
    "price" => 56.00,
    "n_rooms" => 1,
    "n_bathrooms" => 1,
    "n_beds" => 1,
    "square_meters" => 42,
    "cover_image" => "uploads/jazz-house-roma.webp",
    "is_visible" => 1
  ],
  [
    "title" => "555 Rebora International",
    "category" => "Appartamento",
    "address" =>  "Via Giovanni Guareschi, 66, 00143 Roma RM",
    "price" => 38.00,
    "n_rooms" => 1,
    "n_bathrooms" => 1,
    "n_beds" => 1,
    "square_meters" => 20,
    "cover_image" => "uploads/555-rebora-international.webp",
    "is_visible" => 0
  ],
  [
    "title" => "La Casa del Cardellino",
    "category" => "Villa",
    "address" =>  "Via Fonte Bandusia, 14, 00026 Licenza RM",
    "price" => 84.00,
    "n_rooms" => 2,
    "n_bathrooms" => 2,
    "n_beds" => 2,
    "square_meters" => 68,
    "cover_image" => "uploads/la-casa-del-cardellino.webp",
    "is_visible" => 1
  ],
  [
    "title" => "Appartamento al Vaticano",
    "category" => "Appartamento",
    "address" =>  "Via Fonte Bandusia, 14, 00026 Licenza RM",
    "price" => 78.00,
    "n_rooms" => 3,
    "n_bathrooms" => 1,
    "n_beds" => 2,
    "square_meters" => 60,
    "cover_image" => "uploads/la-casa-del-cardellino.webp",
    "is_visible" => 1
  ],
  [
    "title" => "Appartamento Duomo con vista cattedrale",
    "category" => "Appartamento",
    "address" =>  "Via dell' Oriuolo, 20, 50122 Firenze FI",
    "price" => 142.00,
    "n_rooms" => 2,
    "n_bathrooms" => 1,
    "n_beds" => 1,
    "square_meters" => 45,
    "cover_image" => "uploads/appartamento-duomo-con-vista-cattedrale.webp",
    "is_visible" => 1
  ],
  [
    "title" => "Amore e Rinascimento suite con Jacuzzi",
    "category" => "Luxury Apartment",
    "address" =>  "Via dei Pandolfini, 24, 50122 Firenze FI",
    "price" => 275.00,
    "n_rooms" => 3,
    "n_bathrooms" => 2,
    "n_beds" => 3,
    "square_meters" => 85,
    "cover_image" => "uploads/amore-e-rinascimento-suite-con-jacuzzi.webp",
    "is_visible" => 1
  ],
  [
    "title" => "Medici 's Apt",
    "category" => "Appartamento",
    "address" =>  "Via Faenza, 84, 50123 Firenze FI",
    "price" => 177.00,
    "n_rooms" => 2,
    "n_bathrooms" => 1,
    "n_beds" => 1,
    "square_meters" => 58,
    "cover_image" => "uploads/medicis-apt.webp",
    "is_visible" => 1
  ],
  [
    "title" => "L'Angolo di Ponte Vecchio",
    "category" => "Appartamento",
    "address" =>  "Via Faenza, 84, 50123 Firenze FI",
    "price" => 149.00,
    "n_rooms" => 1,
    "n_bathrooms" => 1,
    "n_beds" => 1,
    "square_meters" => 45,
    "cover_image" => "uploads/langolo-di-ponte-vecchio.webp",
    "is_visible" => 0
  ],
  [
    "title" => "Felice Firenze Ponte Vecchio",
    "category" => "BnB",
    "address" =>  "Via Faenza, 84, 50123 Firenze FI",
    "price" => 123.00,
    "n_rooms" => 2,
    "n_bathrooms" => 1,
    "n_beds" => 1,
    "square_meters" => 49,
    "cover_image" => "uploads/felice-firenze-ponte-vecchio.webp",
    "is_visible" => 1
  ],
  [
    "title" => "Tornabuoni Studio",
    "category" => "Appartamento",
    "address" =>  "Via delle Belle Donne, 33, 50123 Firenze FI",
    "price" => 130.00,
    "n_rooms" => 1,
    "n_bathrooms" => 1,
    "n_beds" => 1,
    "square_meters" => 40,
    "cover_image" => "uploads/tornabuoni-studio.webp",
    "is_visible" => 1
  ],
  [
    "title" => "Santo Stefano Balcony",
    "category" => "Appartamento",
    "address" =>  "Calle Vitturi o Falier, 2934, 30124 Venezia VE",
    "price" => 170.00,
    "n_rooms" => 2,
    "n_bathrooms" => 1,
    "n_beds" => 2,
    "square_meters" => 60,
    "cover_image" => "uploads/santo-stefano-balcony.webp",
    "is_visible" => 1
  ],
  [
    "title" => "Pisani Suite sul Canale",
    "category" => "Luxury Apartment",
    "address" =>  "Ponte dei Bareteri, San Marco, 580, 30124 Venezia VE",
    "price" => 275.00,
    "n_rooms" => 1,
    "n_bathrooms" => 1,
    "n_beds" => 1,
    "square_meters" => 45,
    "cover_image" => "uploads/pisani-suite-sul-canale.webp",
    "is_visible" => 1
  ],
  [
    "title" => "Grande stanza al centro di Palermo",
    "category" => "Appartamento",
    "address" =>  "Via Vittorio Emanuele, 293, 90133 Palermo PA",
    "price" => 146.00,
    "n_rooms" => 2,
    "n_bathrooms" => 2,
    "n_beds" => 2,
    "square_meters" => 60,
    "cover_image" => "uploads/5b609170-0b2c-4f1e-b9c4-de09da498647.webp",
    "is_visible" => 1
  ],
  [
    "title" => "La Grande Terrazza",
    "category" => "Luxury Apartment",
    "address" =>  "Via Collegio Giusino, 15, 90134 Palermo PA",
    "price" => 80.00,
    "n_rooms" => 1,
    "n_bathrooms" => 1,
    "n_beds" => 1,
    "square_meters" => 40,
    "cover_image" => "uploads/aea36ba2-d9b0-4449-9b45-5d8fd54c7057.webp",
    "is_visible" => 1
  ],
  [
    "title" => "Alla terrazza di Piero e Nicole",
    "category" => "Villa",
    "address" =>  "Via Incoronazione, 4, 90134 Palermo PA",
    "price" => 120.00,
    "n_rooms" => 2,
    "n_bathrooms" => 1,
    "n_beds" => 2,
    "square_meters" => 50,
    "cover_image" => "uploads/ee01999a-66b9-46f0-874a-a0bb688ed6b0.webp",
    "is_visible" => 1
  ],
  [
    "title" => "Appartamento con giardino vicino alle spiagge",
    "category" => "Appartamento",
    "address" =>  "Via Regina Elena, 75, 07026 Olbia SS",
    "price" => 210.00,
    "n_rooms" => 2,
    "n_bathrooms" => 1,
    "n_beds" => 1,
    "square_meters" => 50,
    "cover_image" => "uploads/8650bac5-9f1e-42c2-b1b9-1db8edd16720.webp",
    "is_visible" => 1
  ],
  [
    "title" => "Casa Mir.Ago immersa nella Natura-2 passi dal mare",
    "category" => "Luxury Apartment",
    "address" =>  "Via Roma, 14, 07026 Olbia SS",
    "price" => 264.00,
    "n_rooms" => 4,
    "n_bathrooms" => 2,
    "n_beds" => 3,
    "square_meters" => 89,
    "cover_image" => "uploads/e9913cbc-fc7c-45a6-a1b0-dca86884ff7c.webp",
    "is_visible" => 1
  ],
  [
    "title" => "Le Dimore di Budoni Bilocale",
    "category" => "Villa",
    "address" =>  "Viale Isola Bianca, 3, 07026 Olbia SS",
    "price" => 215.00,
    "n_rooms" => 3,
    "n_bathrooms" => 2,
    "n_beds" => 4,
    "square_meters" => 90,
    "cover_image" => "uploads/ffce9694-3419-4564-9d21-89fa605e3391.webp",
    "is_visible" => 1
  ],
  [
    "title" => "Sardegna Vacanza Navarrese al mare",
    "category" => "Villa",
    "address" =>  "Via Indonesia, 7, 07026 Olbia SS",
    "price" => 326.00,
    "n_rooms" => 4,
    "n_bathrooms" => 2,
    "n_beds" => 4,
    "square_meters" => 110,
    "cover_image" => "uploads/b33d287a-18bd-44de-be44-a504c0c22141.webp",
    "is_visible" => 1
  ],
  [
    "title" => "Home Loft Belle Arti",
    "category" => "Appartamento",
    "address" =>  "Via Caduti di Amola, 11-31, 40132 Bologna BO",
    "price" => 280.00,
    "n_rooms" => 4,
    "n_bathrooms" => 2,
    "n_beds" => 2,
    "square_meters" => 100,
    "cover_image" => "uploads/2dc21969-c035-487a-af58-82e91f26c617.webp",
    "is_visible" => 1
  ],
  [
    "title" => "Bilocale. Sasso Marconi",
    "category" => "Luxury Apartments",
    "address" =>  "Via Massimo D'Antona, 40069 Riale BO",
    "price" => 240.00,
    "n_rooms" => 2,
    "n_bathrooms" => 1,
    "n_beds" => 2,
    "square_meters" => 120,
    "cover_image" => "uploads/6a2bed02-e32d-4335-a307-bbb731c98434.webp",
    "is_visible" => 1
  ],
  [
    "title" => "Appartamento ad uso esclusivo",
    "category" => "Appartamento",
    "address" =>  "Via Risorgimento, 182, 40069 Zola Predosa BO",
    "price" => 200.00,
    "n_rooms" => 2,
    "n_bathrooms" => 1,
    "n_beds" => 2,
    "square_meters" => 67,
    "cover_image" => "uploads/c8fc08a2-ed5b-41b2-9745-d26e0e4f7c50.webp",
    "is_visible" => 1
  ],
  [
    "title" => "Casa Maja",
    "category" => "Villa",
    "address" =>  "Via Duca degli Abruzzi, 36, 66040 Roccascalegna CH",
    "price" => 180.00,
    "n_rooms" => 2,
    "n_bathrooms" => 2,
    "n_beds" => 2,
    "square_meters" => 59,
    "cover_image" => "uploads/58742bab-f5b3-4f92-930f-14f0e4abf836.webp",
    "is_visible" => 0
  ],
  [
    "title" => "La campagna a Venezia",
    "category" => "Casa",
    "address" =>  "Isola S. Erasmo, 45, 30121 Venezia VE",
    "price" => 190.00,
    "n_rooms" => 5,
    "n_bathrooms" => 2,
    "n_beds" => 7,
    "square_meters" => 95,
    "cover_image" => "uploads/la-campagna-a-venezia.webp",
    "is_visible" => 1
  ],
  [
    "title" => "Ca' al campanile con splendida vista",
    "category" => "Casa",
    "address" =>  "Calle de le Conterie, 21, 30141 Venezia VE",
    "price" => 105.00,
    "n_rooms" => 3,
    "n_bathrooms" => 1,
    "n_beds" => 2,
    "square_meters" => 64,
    "cover_image" => "uploads/ca-al-campanile-con-splendida-vista.webp",
    "is_visible" => 1
  ],
  [
    "title" => "Appartamento Luxury Panoramico",
    "category" => "Luxury Apartment",
    "address" =>  "Via Marino Turchi, 21, 80132 Napoli NA",
    "price" => 244.00,
    "n_rooms" => 3,
    "n_bathrooms" => 1,
    "n_beds" => 4,
    "square_meters" => 64,
    "cover_image" => "uploads/appartamento-luxury-panoramico.webp",
    "is_visible" => 1
  ],
  [
    "title" => "Casa Misano",
    "category" => "Appartamento",
    "address" =>  "Via Miliscola, 4, 80070 Bacoli NA",
    "price" => 115.00,
    "n_rooms" => 3,
    "n_bathrooms" => 2,
    "n_beds" => 4,
    "square_meters" => 68,
    "cover_image" => "uploads/casa-misano.webp",
    "is_visible" => 1
  ],
  [
    "title" => "L'onda, nuovo appartamento in centro a Bologna",
    "category" => "Appartamento",
    "address" =>  "Via Ugo Bassi, 5, 40121 Bologna BO",
    "price" => 110.00,
    "n_rooms" => 2,
    "n_bathrooms" => 1,
    "n_beds" => 1,
    "square_meters" => 42,
    "cover_image" => "uploads/londa-nuovo-appartamento-in-centro-a-bologna.webp",
    "is_visible" => 1
  ],
  [
    "title" => "Dimora storica in centro",
    "category" => "Appartamento",
    "address" =>  "Via Mascarella, 53, 40126 Bologna BO",
    "price" => 129.00,
    "n_rooms" => 2,
    "n_bathrooms" => 1,
    "n_beds" => 2,
    "square_meters" => 42,
    "cover_image" => "uploads/dimora-storica-in-centro.webp",
    "is_visible" => 1
  ],
  [
    "title" => "Dimora Panesa, spaziosa e centrale",
    "category" => "Appartamento",
    "address" =>  "Via Irnerio, 43, 40126 Bologna BO",
    "price" => 200.00,
    "n_rooms" => 3,
    "n_bathrooms" => 1,
    "n_beds" => 3,
    "square_meters" => 56,
    "cover_image" => "uploads/dimora-panesa-spaziosa-centrale.webp",
    "is_visible" => 1
  ],
  [
    "title" => "Appartamento Alle Due Torri",
    "category" => "Appartamento",
    "address" =>  "Via De' Giudei, 3, 40126 Bologna BO",
    "price" => 90.00,
    "n_rooms" => 3,
    "n_bathrooms" => 1,
    "n_beds" => 4,
    "square_meters" => 61,
    "cover_image" => "uploads/appartamento-alle-due-torri.webp",
    "is_visible" => 0
  ],
  [
    "title" => "Suite Goito 3",
    "category" => "Appartamento",
    "address" =>  "Via De' Giudei, 3, 40126 Bologna BO",
    "price" => 115.00,
    "n_rooms" => 2,
    "n_bathrooms" => 1,
    "n_beds" => 2,
    "square_meters" => 40,
    "cover_image" => "uploads/suite-goito-3.webp",
    "is_visible" => 1
  ],
  [
    "title" => "The view: attico panoramico a Padova",
    "category" => "Appartamento",
    "address" =>  "Via Flavio Busonera, 6, 35139 Padova PD",
    "price" => 120.00,
    "n_rooms" => 2,
    "n_bathrooms" => 1,
    "n_beds" => 1,
    "square_meters" => 50,
    "cover_image" => "uploads/the-view-attico-panoramico-a-padova.webp",
    "is_visible" => 1
  ],
  [
    "title" => "A&F apartment Padova Centro Storico",
    "category" => "Appartamento",
    "address" =>  "Via Zabarella, 38, 35121 Padova PD",
    "price" => 105.00,
    "n_rooms" => 2,
    "n_bathrooms" => 1,
    "n_beds" => 1,
    "square_meters" => 48,
    "cover_image" => "uploads/af-apartment-padova-centro-storico.webp",
    "is_visible" => 1
  ],
  [
    "title" => "Il Diamante di Piazza Dei Signori",
    "category" => "Appartamento",
    "address" =>  "Via dei Da Carrara, 18, 35139 Padova PD",
    "price" => 120.00,
    "n_rooms" => 3,
    "n_bathrooms" => 1,
    "n_beds" => 4,
    "square_meters" => 65,
    "cover_image" => "uploads/il-diamante-di-piazza-dei-signori.webp",
    "is_visible" => 1
  ],
  [
    "title" => "Fuga romantica nel cuore di Padova",
    "category" => "Appartamento",
    "address" =>  "Piazza delle Erbe, 50, 35122 Padova PD",
    "price" => 120.00,
    "n_rooms" => 2,
    "n_bathrooms" => 1,
    "n_beds" => 2,
    "square_meters" => 65,
    "cover_image" => "uploads/fuga-romantica-nel-cuore-di-padova.webp",
    "is_visible" => 1
  ],
  [
  "title" => "Junior Suite con Wi-Fi e A/C",
  "category" => "Appartamento",
  "address" => "Via S. Dalmazzo, 26, 10122 Torino TO",
  "price" => 81.00,
  "n_rooms" => 1,
  "n_bathrooms" => 1,
  "n_beds" => 1,
  "square_meters" => 65,
  "cover_image" => "uploads/31dc7a51.webp",
  "is_visible" => 1
  ],
  [
  "title" => "Dora 's House",
  "category" => "Appartamento",
  "address" => "Via Caserta, 6, 10144 Torino TO",
  "price" => 48.00,
  "n_rooms" => 1,
  "n_bathrooms" => 1,
  "n_beds" => 1,
  "square_meters" => 75,
  "cover_image" => "uploads/45215b74.webp",
  "is_visible" => 1
  ],
  [
  "title" => "Alloggio Zona università",
  "category" => "Appartamento",
  "address" => "Via Buonarroti Michelangelo, 57, 10095 Grugliasco TO",
  "price" => 54.00,
  "n_rooms" => 1,
  "n_bathrooms" => 1,
  "n_beds" => 1,
  "square_meters" => 43,
  "cover_image" => "uploads/1ab0a91e.webp",
  "is_visible" => 1
  ],
  [
  "title" => "Casa Baciu: Piacevole bilocale in zona Lingotto",
  "category" => "Appartamento",
  "address" => "Via Rocca de' Baldi, 16, 10127 Torino TO",
  "price" => 50.00,
  "n_rooms" => 1,
  "n_bathrooms" => 1,
  "n_beds" => 2,
  "square_meters" => 63,
  "cover_image" => "uploads/fb079bee.webp",
  "is_visible" => 0
  ],
  [
  "title" => "Top loft in centro città",
  "category" => "Casa",
  "address" => "Piazza Moncenisio, 4, 10143 Torino TO",
  "price" => 33.00,
  "n_rooms" => 1,
  "n_bathrooms" => 1,
  "n_beds" => 1,
  "square_meters" => 70,
  "cover_image" => "uploads/97f3fbe8.webp",
  "is_visible" => 1
  ],
  [
  "title" => "Bilocale panoramico vista Monviso",
  "category" => "Appartamento",
  "address" => "Corso Benedetto Croce, 38/10, 10135 Torino TO",
  "price" => 35.00,
  "n_rooms" => 1,
  "n_bathrooms" => 1,
  "n_beds" => 1,
  "square_meters" => 48,
  "cover_image" => "uploads/caff5fa8.webp",
  "is_visible" => 1
  ],
  [
  "title" => "Casa Baciu: Fresca ed Elegante vicino alla Metro",
  "category" => "Casa",
  "address" => "Via Genova, 243, 10127 Torino TO",
  "price" => 51.00,
  "n_rooms" => 1,
  "n_bathrooms" => 1,
  "n_beds" => 2,
  "square_meters" => 79,
  "cover_image" => "uploads/be387f85.webp",
  "is_visible" => 1
  ],
  [
  "title" => "Monolocale Vicinanza Tribunale",
  "category" => "Appartamento",
  "address" => "Via Malta, 15/A, 10141 Torino TO",
  "price" => 28.00,
  "n_rooms" => 1,
  "n_bathrooms" => 1,
  "n_beds" => 1,
  "square_meters" => 29,
  "cover_image" => "uploads/e1008ea7.webp",
  "is_visible" => 1
  ],
  [
  "title" => "[Agape Terrace] Attico a due passi dal centro",
  "category" => "Appartamento",
  "address" => "Via Cernaia, 27, 10121 Torino TO",
  "price" => 59.00,
  "n_rooms" => 1,
  "n_bathrooms" => 1,
  "n_beds" => 1,
  "square_meters" => 63,
  "cover_image" => "uploads/876efeed.webp",
  "is_visible" => 1
  ],
  [
  "title" => "GRAN SUITE METRO MONTEGRAPPA",
  "category" => "Casa",
  "address" => "Via Exilles, 54, 10146 Torino TO",
  "price" => 57.00,
  "n_rooms" => 1,
  "n_bathrooms" => 1,
  "n_beds" => 2,
  "square_meters" => 59,
  "cover_image" => "uploads/2a5ca92f.webp",
  "is_visible" => 1
  ],
  [
  "title" => "AventisTecnoliving",
  "category" => "Appartamento",
  "address" => "Via Dalmazia, 17/C, 25126 Brescia BS",
  "price" => 71.00,
  "n_rooms" => 1,
  "n_bathrooms" => 1,
  "n_beds" => 1,
  "square_meters" => 89,
  "cover_image" => "uploads/9fbfa11e.webp",
  "is_visible" => 1
  ],
  [
  "title" => "Brixia Charm Studio",
  "category" => "Appartamento",
  "address" => "Via Trento, 74/A, 25128 Brescia BS",
  "price" => 65.00,
  "n_rooms" => 1,
  "n_bathrooms" => 1,
  "n_beds" => 1,
  "square_meters" => 85,
  "cover_image" => "uploads/b55a94fd.webp",
  "is_visible" => 1
  ],
  [
  "title" => "La casa di Conte Cavour",
  "category" => "Appartamento",
  "address" => "Via S. Martino della Battaglia, 3, 25121 Brescia BS",
  "price" => 64.00,
  "n_rooms" => 1,
  "n_bathrooms" => 1,
  "n_beds" => 1,
  "square_meters" => 95,
  "cover_image" => "uploads/4a589c6e.webp",
  "is_visible" => 1
  ],
  [
  "title" => "Brixia Time Case. Stanza singola giardino in città",
  "category" => "Appartamento",
  "address" => "Via S. Martino della Battaglia, 3, 25121 Brescia BS",
  "price" => 35.00,
  "n_rooms" => 1,
  "n_bathrooms" => 1,
  "n_beds" => 1,
  "square_meters" => 26,
  "cover_image" => "uploads/718c0fbb.webp",
  "is_visible" => 1
  ],
  [
  "title" => "Grazioso Loft nel cuore di Seregno",
  "category" => "Appartamento",
  "address" => "Via Giuseppe Garibaldi, 9, 20831 Seregno MB",
  "price" => 77.00,
  "n_rooms" => 1,
  "n_bathrooms" => 1,
  "n_beds" => 1,
  "square_meters" => 66,
  "cover_image" => "uploads/54a3c63e.webp",
  "is_visible" => 1
  ],
  [
  "title" => "Appartamento in centro Cogliate",
  "category" => "Appartamento",
  "address" => "Via Giosuè Carducci, 17, 20815 Cogliate MB",
  "price" => 76.00,
  "n_rooms" => 1,
  "n_bathrooms" => 1,
  "n_beds" => 2,
  "square_meters" => 53,
  "cover_image" => "uploads/9e8d2d84.webp",
  "is_visible" => 1
  ],
  [
  "title" => "Milano P.le Udine - Palmanova Flat Full",
  "category" => "Appartamento",
  "address" => "Via Tolmezzo, 12/7, 20132 Milano MI",
  "price" => 54.00,
  "n_rooms" => 1,
  "n_bathrooms" => 1,
  "n_beds" => 1,
  "square_meters" => 44,
  "cover_image" => "uploads/589907cb.webp",
  "is_visible" => 1
  ],
  [
  "title" => "appartamento monolocale comodo per fiera",
  "category" => "Appartamento",
  "address" => "Via Luigi Capuana, 21, 20017 Rho MI",
  "price" => 40.00,
  "n_rooms" => 1,
  "n_bathrooms" => 1,
  "n_beds" => 2,
  "square_meters" => 34,
  "cover_image" => "uploads/2b8e32b0.webp",
  "is_visible" => 1
  ],
  [
  "title" => "Accogliente Brianza",
  "category" => "Appartamento",
  "address" => "Via Trento, 1, 22040 Brenna CO",
  "price" => 57.00,
  "n_rooms" => 1,
  "n_bathrooms" => 1,
  "n_beds" => 2,
  "square_meters" => 34,
  "cover_image" => "uploads/91c7d5d6.webp",
  "is_visible" => 1
  ],
  [
  "title" => "Oasi delle Betulle",
  "category" => "Casa",
  "address" => "Salita dei Cappuccini, 20, 22100 Como CO",
  "price" => 103.00,
  "n_rooms" => 1,
  "n_bathrooms" => 1,
  "n_beds" => 2,
  "square_meters" => 63,
  "cover_image" => "uploads/15ba2f97.webp",
  "is_visible" => 1
  ],
  [
  "title" => "Al casello n.2",
  "category" => "Appartamento",
  "address" => "P.le S. Gottardo, 1, 22100 Como CO",
  "price" => 284.00,
  "n_rooms" => 2,
  "n_bathrooms" => 1,
  "n_beds" => 3,
  "square_meters" => 94,
  "cover_image" => "uploads/dc98f565.webp",
  "is_visible" => 1
  ],
  [
  "title" => "La casa di Aurora",
  "category" => "Appartamento",
  "address" => "Via Fiume, 2, 70121 Bari BA",
  "price" => 120.00,
  "n_rooms" => 4,
  "n_bathrooms" => 1,
  "n_beds" => 2,
  "square_meters" => 80,
  "cover_image" => "uploads/1fad9a2e-8f86-412e-89da-8b3797b98c1e.webp",
  "is_visible" => 1
  ],
  [
  "title" => "Piccola stanza per 1/2 persone. BA07200691000021485",
  "category" => "Appartamento",
  "address" => "Via Quarnaro, 20-2, 70121 Bari BA",
  "price" => 36.00,
  "n_rooms" => 5,
  "n_bathrooms" => 2,
  "n_beds" => 3,
  "square_meters" => 90,
  "cover_image" => "uploads/52e302af-ee3b-489b-8bdf-90fe49daecbc.webp",
  "is_visible" => 1
  ],
  [
  "title" => "The Red Dragon",
  "category" => "Appartamento",
  "address" => "Via Sabino Fiorese, 70121 Bari BA",
  "price" => 85.00,
  "n_rooms" => 3,
  "n_bathrooms" => 2,
  "n_beds" => 3,
  "square_meters" => 80,
  "cover_image" => "uploads/262be06e-3b38-4dda-b504-1275baf1c707.webp",
  "is_visible" => 1
  ],
  [
  "title" => "Il Castello del Drago",
  "category" => "Appartamento",
  "address" => "Piazza Federico II di Svevia, 11-4, 70122 Bari BA",
  "price" => 114.00,
  "n_rooms" => 4,
  "n_bathrooms" => 1,
  "n_beds" => 2,
  "square_meters" => 120,
  "cover_image" => "uploads/5e36e33c-3200-47de-b50c-d8fff08a5c75.webp",
  "is_visible" => 1
  ],
  [
  "title" => "Nel baricentro del centro storico di Bari",
  "category" => "Appartamento",
  "address" => "Str. dei Dottula, 18, 70122 Bari BA",
  "price" => 50.00,
  "n_rooms" => 3,
  "n_bathrooms" => 2,
  "n_beds" => 3,
  "square_meters" => 60,
  "cover_image" => "uploads/f219ffd0-b9cc-4527-ac30-f0b46f5b05d7.webp",
  "is_visible" => 1
  ],
  [
  "title" => "Attico Nel Centro Storico - |Vista Cattedrale|",
  "category" => "Villa",
  "address" => "Str. dei Dottula, 18, 70122 Bari BA",
  "price" => 137.00,
  "n_rooms" => 5,
  "n_bathrooms" => 2,
  "n_beds" => 4,
  "square_meters" => 120,
  "cover_image" => "uploads/abce6ff9-3c07-4925-bf9b-e62af9ddd857.webp",
  "is_visible" => 1
  ],
  [
  "title" => "Passeggiata, parco di Nervi, residence Vittoria",
  "category" => "Appartamento",
  "address" => "Corso Italia, 3, 16145 Genova GE",
  "price" => 58.00,
  "n_rooms" => 1,
  "n_bathrooms" => 1,
  "n_beds" => 3,
  "square_meters" => 50,
  "cover_image" => "uploads/efc1d4d1-7e2f-4255-a08f-7d8fe3b46545.webp",
  "is_visible" => 1
  ],
  [
  "title" => "The Downtown attic",
  "category" => "Appartamento",
  "address" => "Via Nizza, 94, 16145 Genova GE",
  "price" => 96.00,
  "n_rooms" => 3,
  "n_bathrooms" => 1,
  "n_beds" => 2,
  "square_meters" => 90,
  "cover_image" => "uploads/082e39e2-570c-4026-900e-af3ee953ac1b.webp",
  "is_visible" => 1
  ],
  [
  "title" => "Sentirsi a casa vicino al centro",
  "category" => "Appartamento",
  "address" => "Via Colombo, 61, 16121 Genova GE",
  "price" => 66.00,
  "n_rooms" => 5,
  "n_bathrooms" => 2,
  "n_beds" => 3,
  "square_meters" => 80,
  "cover_image" => "uploads/bbdac71c-3880-4ca6-a79f-2cfc8a09d0d5.webp",
  "is_visible" => 1
  ],
  [
  "title" => "Stanza Privata Zona Aeroporto (vicino al centro)",
  "category" => "Appartamento",
  "address" => "Via XX Settembre, 20, 16121 Genova GE",
  "price" => 71.00,
  "n_rooms" => 4,
  "n_bathrooms" => 1,
  "n_beds" => 2,
  "square_meters" => 120,
  "cover_image" => "uploads/dfc854f8-779b-4412-849d-80c2b02658ec.webp",
  "is_visible" => 1
  ],
  [
  "title" => "Principe Terzo",
  "category" => "Appartamento",
  "address" => "Via Innocenzo Frugoni, 15, 16121 Genova GE",
  "price" => 112.00,
  "n_rooms" => 3,
  "n_bathrooms" => 2,
  "n_beds" => 3,
  "square_meters" => 70,
  "cover_image" => "uploads/e5a6381f-a5d9-449c-ab8c-ac13791f3a54.webp",
  "is_visible" => 1
  ],
  [
  "title" => "Casa Vacanze Liguria",
  "category" => "Villa",
  "address" => "3/26, Via Fieschi, 16121 Genova GE",
  "price" => 137.00,
  "n_rooms" => 5,
  "n_bathrooms" => 2,
  "n_beds" => 4,
  "square_meters" => 120,
  "cover_image" => "uploads/74179196-834c-4581-ab12-087155c459da.webp",
  "is_visible" => 1
  ],
  [
    "title" => "Appartamento vista mare Rimini",
    "category" => "Appartamento",
    "address" => "Viale Vittorio Veneto, 10, 47921 Rimini RN",
    "price" => 100.00,
    "n_rooms" => 3,
    "n_bathrooms" => 1,
    "n_beds" => 2,
    "square_meters" => 52,
    "cover_image" => "uploads/appartamento-vista-mare-rimini.webp",
    "is_visible" => 1
  ],
  [
    "title" => "Grazioso appartamento a Rimini al mare",
    "category" => "Appartamento",
    "address" => "Via Paolo e Francesca, 9, 47921 Rimini RN",
    "price" => 129.00,
    "n_rooms" => 2,
    "n_bathrooms" => 1,
    "n_beds" => 2,
    "square_meters" => 48,
    "cover_image" => "uploads/grazioso-appartamento-a-rimini-al-mare.webp",
    "is_visible" => 1
  ],
  [
    "title" => "Gemma nel cuore di Marina Centro",
    "category" => "Casa",
    "address" => "Via Paolo e Francesca, 1, 47921 Rimini RN",
    "price" => 129.00,
    "n_rooms" => 3,
    "n_bathrooms" => 2,
    "n_beds" => 3,
    "square_meters" => 64,
    "cover_image" => "uploads/gemma-nel-cuore-di-marina-centro.webp",
    "is_visible" => 1
  ],
  [
    "title" => "Sea View Embassy Apartment",
    "category" => "Appartamento",
    "address" => "Viale Dandolo, 18, 47921 Rimini RN",
    "price" => 110.00,
    "n_rooms" => 2,
    "n_bathrooms" => 1,
    "n_beds" => 2,
    "square_meters" => 53,
    "cover_image" => "uploads/sea-view-embassy.apartment.webp",
    "is_visible" => 1
  ],
  [
    "title" => "Villa con piscina privata a Rimini",
    "category" => "Villa",
    "address" => "Viale Cristoforo Colombo, 14, 47921 Rimini RN",
    "price" => 656.00,
    "n_rooms" => 9,
    "n_bathrooms" => 5,
    "n_beds" => 7,
    "square_meters" => 160,
    "cover_image" => "uploads/villa-con-piscina-privata-a-rimini.webp",
    "is_visible" => 1
  ],
  [
    "title" => "Volare nel cuore di Marina Centro",
    "category" => "Casa",
    "address" => "Viale Alfredo Cappellini, 2, 47921 Rimini RN",
    "price" => 140.00,
    "n_rooms" => 3,
    "n_bathrooms" => 1,
    "n_beds" => 2,
    "square_meters" => 56,
    "cover_image" => "uploads/volare-nel-cuore-di-marina-centro.webp",
    "is_visible" => 1
  ],
  [
    "title" => "Prestigioso bilocale al mare",
    "category" => "Casa",
    "address" => "Viale Amerigo Vespucci, 38, 47921 Rimini RN",
    "price" => 96.00,
    "n_rooms" => 2,
    "n_bathrooms" => 1,
    "n_beds" => 1,
    "square_meters" => 41,
    "cover_image" => "uploads/prestigioso-bilocale-al-mare.webp",
    "is_visible" => 1
  ],
  [
    "title" => "Appartamento Marina Centro frontemare con piscina",
    "category" => "Appartamento",
    "address" => "Lungomare Claudio Tintori, 5, 47921 Rimini RN",
    "price" => 189.00,
    "n_rooms" => 3,
    "n_bathrooms" => 2,
    "n_beds" => 2,
    "square_meters" => 54,
    "cover_image" => "uploads/appartamento-marina-centro-frontemare-con-piscina.webp",
    "is_visible" => 1
  ]
];
